package Handler;

public enum ResponseStatus {
    INVALID_USERNAME,
    VALID_USERNAME,
    SIGNUP_INVALID,
    SIGNUP_VALID,
    SIGN_IN_VALID,
    SIGN_IN_INVALID,
    SIGN_OUT_VALID,
    VALID_STATUS,
    INVALID_STATUS,
    PROFILE_PHOTO,
    EMPTY_FRIEND_REQUEST_LIST,
    NOT_EMPTY_FRIEND_REQUEST_LIST,
    DUPLICATE_FRIEND_REQUEST,
    FRIEND_REQUEST_TO_FRIEND,
    VALID_FRIEND_REQUEST,
    VALID_ACCEPT_FRIEND_REQUEST,
    INVALID_ACCEPT_FRIEND_REQUEST,
    VALID_DELETE_FRIEND_REQUEST,
    INVALID_DELETE_FRIEND_REQUEST;
}
